### ISSUE TITLE
Test a whole slew of compression algorithms

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/snacc#11]
Gzip
bzip2
lempel-ziv welch

Any others that you can think of
Let's implement and test them :D

**Comment by souravsingh** [comment]
LZMA currently takes 25 secs to compress. I am now looking into other algorithms

**Comment by tamario** [comment]
I will quickly code gzip and bzip2

**Comment by souravsingh** [comment]
A few run-time analyses done so far-

Bzip2 takes 2 secs
GZIP takes 18.5 secs
Zlib takes 2.8 s

**Comment by souravsingh** [comment]
The results are using timeit through best of 3 runs.

**Comment by souravsingh** [comment]
Does anyone wish to cross-check these results?
