### ISSUE TITLE
Introductions & Initial Setup

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/snacc#3]
Hello everyone! As we get ready for the event, I'd like to start preparing potential issues that team members can take on. To help with that (and to start getting to know each other), could people please comment on this issue with a brief overview of:

- General background info
- Previous hackseq or other hackathon experience
- Whether you'll be attending in Vancouver or working remotely (and if remote, which time zone?)

To start, I am a second year MSc student in Computer Science at Simon Fraser University. I was a participant for hackseq17, and decided to lead my own project this year. This project represents some of the research that I'm personally interested in, but have had to put aside due to other priorities. 

For this hackathon, you will need to be able to run Python3 locally. I HIGHLY recommend [Anaconda](https://www.anaconda.com/download/), as it includes all the packages we need and makes installing future dependencies a breeze. Anaconda will also allow you to create Jupyter notebooks, which I regularly use to demonstrate code and benchmark our pipeline. Thanks to the Genome Science Center, we also have access to a high performance computing cluster (unscheduled), which I will link to you all on Friday. 

Finally, we have a slack channel [here](https://join.slack.com/t/hackseq18/shared_invite/enQtNDQ4NDg5MzQ3NTU2LTVlOWVlZTNhM2Y1YTNmNTEyMzQwYTNmOWIxYTAwNjQ0MWMzYzFlMjAxYWYxNzVjNWY5OTYzZTc1ZjRhNTMyYTA). I'll do my best to relay important information we discuss in-person onto our Slack channel so that remote participants can keep up with our progress. 

See ya'll on Friday!

**Comment by bakeronit** [comment]
Hello! My name is Jia. I am from James Cook University studying marine biology in Australia(AEST time zone). So pity I can only do this remotely. I am very interested in bioinformatics and computer sciences. This is my first time to join hackseq and I hope I can be less useless...
I use python scripts a lot in my work but I'm not very familiar with python scientific computing tools. 
I think I can learn a lot from you:)
 Cheers

**Comment by souravsingh** [comment]
Hello, My name is Sourav. I am from SPPU, Pune and I belong to IST. My interest lies in Machine Learning and High-Throughput Genomics, Phylogenetics and Proteomics. I heard about hackseq in 2017 but couldn't apply in time, so this is my first hackseq hackathon.

I use Python and its associated scientific tools for my analyses and projects and I hope to make a significant contribution to the project.

**Comment by wilcas** [comment]
Hello All,
You can call me Will. I'm a second year graduate student in bioinformatics at UBC. I'm interested manly in linear/generalized linear modelling for epidemiology studies  (Quantitative Trait Loci) and the discovery of gene by environment interaction. 

I participated in last year's HackSeq as well as SVAI's genomics hackathon in SF in summer 2017. Alex and I were both on last year's HackSeq team "FuseBench" where we clinched  a cool second place. We worked on unifying the output of several gene-fusion detecting algorithms to help researchers ask more complex questions (like complex overlaps between spliced genes etc.).

I mainly use R and bash scripting for my current work, but in the past I've worked in python and I have worked with several scientific computing libraries in the past (I've used jupyter notebooks and scientific computing tools in python before, just not on an everyday basis).

**Comment by tamario** [comment]
Hi all, 
My name is Tamar, I am a fourth year undergraduate student here at UBC studying Computer Science and Microbiology. I am interested in pursuing further graduate studies in bioinformatics, focusing mostly on microbial genomics and or microbiome studies. I have been working done 5 months of co-ops in bioinformatics, 4 at the Genome Institute of Singapore and now at the CMMT here in Vancouver. 

I have not participated in hackseq before but i have participated in other hackathons. I have past coding experience in Java, Javascript, R, and most recently Python as well as experience in shell scripting and cluster computing.

**Comment by JanMoat** [comment]
Hi, I’m Jan. I’m in my last undergrad semester at SFU, in the bioinformatics program. I was recently involved in a project concerning the prediction of MICs from genomes, using machine learning methods. My work was primarily in python; I used Conda and Snakemake, and have some experience with parallelization (concurrent futures). I’ve also used a computing cluster and the SLURM workload manager. I haven’t been a part of a hackathon before, so I’m looking forward to the new experience.

Unfortunately, I have a midterm tomorrow morning so I’ll be coming late. If Google Maps is to be trusted, I should see you all at noon. I’ll do my best to catch up on the slack channel on the bus.
