### ISSUE TITLE
[BUG] Distance matrix for test data not as expected

### ISSUE THREAD

**Issue by wilcas** [SweetiePi/snacc#77]
The distance matrix calculated between mystery 1 and 2 is not as expected as of commit  b6a3e52b808bb6b74086f21be3319f1c30736c94

**Comment by SweetiePi** [comment]
is this for btw-disk exclusively? Or for LZMA as well?

**Comment by wilcas** [comment]
I ran gzip. Is there an issue specific to gzip?

**Comment by SweetiePi** [comment]
So far the only compressor that works well is lzma.

**Comment by wilcas** [comment]
The ncd for mystery 1 and itself was around .9?

**Comment by SweetiePi** [comment]
Yep. 0.99 was usually what we got for everything except lzma

**Comment by wilcas** [comment]
Sorry for the confusion then! Check out the pr for a slick new feature
