### ISSUE TITLE
Short description of project

### ISSUE THREAD

**Issue by Benjamin-Lee** [SweetiePi/snacc#78]
For the GitHub project description and Sphinx docs, what is our short project description?

Currently, it is:

> BIOlogical implementation of the Normalized Compression Distance

Do we want to change it to:

> Biological implementation of normalized compression distance

Or something else entirely now that the project name isn't BioNCD?

**Comment by souravsingh** [comment]
NCD for alignment free comparison.

**Comment by wilcas** [comment]
I think NCD for alignment free biological  sequence comparison, or
something to that effect, is good. As long as it includes the distance and
that we are applying it towards biological sequences (faa fasta)

**Comment by Benjamin-Lee** [comment]
Maybe a 🗜, 🧬 (DNA emoji, not currently visible on Macs) or 🌭 is in order.

Cf. https://github.com/COMBINE-lab/salmon, https://github.com/mgalardini/pyseer, https://github.com/johnlees/PopPUNK
