### ISSUE TITLE
Setup.py file

### ISSUE THREAD

**Issue by Benjamin-Lee** [SweetiePi/snacc#9]
Do we want to have a setup.py file to store the dependencies and set up a command line entry point?

**Comment by souravsingh** [comment]
This would be needed, but I wouldn't worry about it right now since we aren't sure about many of the dependencies of the project.

**Comment by Benjamin-Lee** [comment]
Sure -- either way, we should set up a requirements.txt file to simplify environment setup

**Comment by souravsingh** [comment]
Yup, I agree.

**Comment by SweetiePi** [comment]
A requirments.txt would be great!

**Comment by Benjamin-Lee** [comment]
It's there!

**Comment by Benjamin-Lee** [comment]
(along with instructions in the README on how to use it)
