### ISSUE TITLE
NCD for genomes?

### ISSUE THREAD

**Issue by Benjamin-Lee** [SweetiePi/snacc#90]
https://www.mdpi.com/1099-4300/20/6/393

**Comment by wilcas** [comment]
@SweetiePi do you have an idea of what story we're telling from this project?

**Comment by SweetiePi** [comment]
We've been looking into exploring microbial phylogenies using snacc. I'll be sending out an email soon with some updates.

**Comment by Benjamin-Lee** [comment]
Ok great, thanks.
